# Generated by Django 5.2.4 on 2025-07-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('electronics', 'Электроника'), ('clothing', 'Одежда'), ('accessories', 'Аксессуары'), ('kids', 'Товары для детей'), ('sports', 'Спорт'), ('books', 'Книги'), ('furniture', 'Мебель'), ('appliances', 'Бытовая техника')], max_length=100),
        ),
    ]
